name: Using Scripts.yml End-To-End Tests  # Name of the workflow
on: [push]  # Event that triggers the workflow
jobs:
    cypress-run:
        runs-on: ubuntu-latest  # Operating system to run the job on,  and this is i am using
        steps:
        - name: checkout  # Name of the step,  and this is i am using
          uses: actions/checkout@v4 # Action to set up Node.js, and this is i am using

        - name: Run Cypress # tests   Name of the step and this is i am using
          uses: cypress-io/github-action@v6 # Action to set up Node.js,  and this is i am using
            with:
                browser: chrome
                headless: true
                record: true
                start: npm start
                wait-on-timeout: 60
                spec: cypress/integration/*.spec.js
                command: npm run test:button1test1
